version: "2.2"


services:

  # message broker
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3-management-alpine'
    restart: unless-stopped
    networks:
     - broker-network
    ports:
      - 5672:5672
      - 127.0.0.1:15672:15672
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.99
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:?err}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:?derr}
      
    volumes:
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq
      - ./volumes/rabbitmq/logs:/var/log/rabbitmq
    mem_limit: 256M
    mem_reservation: 128M
  
  # key value store
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - redis-network
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/config:/usr/local/etc/redis
      - ./volumes/redis/data:/data
      - ./volumes/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
  
  # monitor of teeworlds servers
  monitor-zcatch-9303:
    container_name: monitor-zcatch-9303
    build: monitor-zcatch/.
    restart: unless-stopped
    networks:
      - broker-network
    depends_on:
      - rabbitmq
    environment:
      # this environment variable overrides any defined 
      # variable in the .env file that is mounted below
      MONITOR_ECON_ADDRESS: 89.163.148.121:9303
      MONITOR_ECON_PASSWORD: ${ECON_PASSWORD:?err}
      MONITOR_BROKER_USER: ${RABBITMQ_USER:?err}
      MONITOR_BROKER_PASSWORD: ${RABBITMQ_PASSWORD:?err} 
  
  monitor-zcatch-9304:
    container_name: monitor-zcatch-9304
    build: monitor-zcatch/.
    restart: unless-stopped
    networks:
      - broker-network
    depends_on:
      - rabbitmq
    environment:
      # this environment variable overrides any defined 
      # variable in the .env file that is mounted below
      MONITOR_ECON_ADDRESS: 89.163.148.121:9304
      MONITOR_ECON_PASSWORD: ${ECON_PASSWORD:?err}
      MONITOR_BROKER_USER: ${RABBITMQ_USER:?err}
      MONITOR_BROKER_PASSWORD: ${RABBITMQ_PASSWORD:?err} 
  
  monitor-zcatch-9305:
    container_name: monitor-zcatch-9305
    build: monitor-zcatch/.
    restart: unless-stopped
    networks:
      - broker-network
    depends_on:
      - rabbitmq
    environment:
      # this environment variable overrides any defined 
      # variable in the .env file that is mounted below
      MONITOR_ECON_ADDRESS: 89.163.148.121:9305
      MONITOR_ECON_PASSWORD: ${ECON_PASSWORD:?err}
      MONITOR_BROKER_USER: ${RABBITMQ_USER:?err}
      MONITOR_BROKER_PASSWORD: ${RABBITMQ_PASSWORD:?err}    
  
  monitor-zcatch-9306:
    container_name: monitor-zcatch-9306
    build: monitor-zcatch/.
    restart: unless-stopped
    networks:
      - broker-network
    depends_on:
      - rabbitmq
    environment:
      # this environment variable overrides any defined 
      # variable in the .env file that is mounted below
      MONITOR_ECON_ADDRESS: 89.163.148.121:9306
      MONITOR_ECON_PASSWORD: ${ECON_PASSWORD:?err}
      MONITOR_BROKER_USER: ${RABBITMQ_USER:?err}
      MONITOR_BROKER_PASSWORD: ${RABBITMQ_PASSWORD:?err}
  
  detect-vpn:
    container_name: detect-vpn
    build: detect-vpn/.
    ulimits:
      core: -1
    networks:
      - broker-network
      - redis-network
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./volumes/detect-vpn:/data
    environment:
      BROKER_USER: ${RABBITMQ_USER:?err}
      BROKER_PASSWORD: ${RABBITMQ_PASSWORD:?derr}
      VPN_BAN_REASON: "VPN - https://zcat.ch/bans"
      VPN_BAN_DURATION: 24h
      BROADCAST_BANS: "false"
      DEFAULT_BAN_COMMAND: "ban {IP} {DURATION:MINUTES} {REASON}"


networks:
  broker-network:
    external: false
  redis-network:
    external: false
