version: "3.8"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    networks:
      - broker-network
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: bridge
    volumes:
      - type: bind
        source: ./volumes/mosquitto/config/
        target: /mosquitto/config
        read_only: true
      - type: bind
        source: ./volumes/mosquitto/data
        target: /mosquitto/data
      - type: bind
        source: ./volumes/mosquitto/log/
        target: /mosquitto/log

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - redis-network
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: bridge
    volumes:
      - type: bind
        source: ./volumes/redis/config
        target: /usr/local/etc/redis
      - type: bind
        source: ./volumes/redis/data
        target: /data
      - type: bind
        source: ./volumes/redis/config/redis.conf
        target: /usr/local/etc/redis/redis.conf
    
  monitor-zcatch-9303:
      container_name: monitor-zcatch-9303
      build: monitor-zcatch/.
      restart: unless-stopped
      networks:
        - broker-network
      depends_on:
        - mosquitto
      environment:
        # this environment variable overrides any defined 
        # variable in the .env file that is mounted below
        MONITOR_ECON_ADDRESS: 89.163.148.121:9303
      # the .env file contains a commonly used password 
      # that one may not want to show here.     
      volumes:
        - type: bind
          source: ./volumes/monitor/.env
          target: /app/.env
  
  monitor-zcatch-9304:
      container_name: monitor-zcatch-9304
      build: monitor-zcatch/.
      restart: unless-stopped
      networks:
        - broker-network
      depends_on:
        - mosquitto
      environment:
        # this environment variable overrides any defined 
        # variable in the .env file that is mounted below
        MONITOR_ECON_ADDRESS: 89.163.148.121:9304
      # the .env file contains a commonly used password 
      # that one may not want to show here.     
      volumes:
        - type: bind
          source: ./volumes/monitor/.env
          target: /app/.env
  
  monitor-zcatch-9305:
    container_name: monitor-zcatch-9305
    build: monitor-zcatch/.
    restart: unless-stopped
    networks:
      - broker-network
    depends_on:
      - mosquitto
    environment:
      # this environment variable overrides any defined 
      # variable in the .env file that is mounted below
      MONITOR_ECON_ADDRESS: 89.163.148.121:9305
    # the .env file contains a commonly used password 
    # that one may not want to show here.     
    volumes:
      - type: bind
        source: ./volumes/monitor/.env
        target: /app/.env
  
  monitor-zcatch-9306:
    container_name: monitor-zcatch-9304
    build: monitor-zcatch/.
    restart: unless-stopped
    networks:
      - broker-network
    depends_on:
      - mosquitto
    environment:
      # this environment variable overrides any defined 
      # variable in the .env file that is mounted below
      MONITOR_ECON_ADDRESS: 89.163.148.121:9306
    # the .env file contains a commonly used password 
    # that one may not want to show here.     
    volumes:
      - type: bind
        source: ./volumes/monitor/.env
        target: /app/.env
  # publisher:
  #   container_name: publisher
  #   build: publisher/.
  #   networks:
  #     - broker-network
  #   depends_on:
  #     - mosquitto
  #   environment:
  #     BROKER_ADDRESS: tcp://mosquitto:1883
  #     BROKER_CLIENT_ID: publisher
  #     BROKER_TOPIC: topic_01

  # detect-vpn:
  #   container_name: detect-vpn
  #   build: detect-vpn/.
  #   networks:
  #     - broker-network
  #   depends_on:
  #     - mosquitto
  #     - redis
  #   volumes:
  #     - type: bind
  #       source: ./volumes/subscriber
  #       target: /data
  #       read_only: false
  #   environment:
  #     BROKER_ADDRESS: tcp://mosquitto:1883
  #     BROKER_CLIENT_ID: detect-vpn
  #     BROKER_TOPIC: topic_01

networks:
  broker-network:
    external: false
  redis-network:
    external: false
